// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddTodo: typeof import('./src/components/todo/AddTodo.vue')['default']
    CommunityIcon: typeof import('./src/components/icons/CommunityIcon.vue')['default']
    DocumentationIcon: typeof import('./src/components/icons/DocumentationIcon.vue')['default']
    EcosystemIcon: typeof import('./src/components/icons/EcosystemIcon.vue')['default']
    Interface: typeof import('./src/components/todo/interface/index.ts')['default']
    Island: typeof import('./node_modules/iles/dist/client/app/components/Island.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    SupportIcon: typeof import('./src/components/icons/SupportIcon.vue')['default']
    Todo: typeof import('./src/components/todo/Todo.vue')['default']
    'Todo.interface': typeof import('./src/components/todo/interface/todo.interface.ts')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    ToolingIcon: typeof import('./src/components/icons/ToolingIcon.vue')['default']
  }
}

export { }
